# Tourist Attractions — Poland + Europe

POLAND_ATTRACTIONS = {
    "gdańsk": [
        {"name": "Długi Targ i Fontanna Neptuna", "type": "landmark", "rating": 4.8, "price": "Free",
         "description": "Serce Gdańska — kolorowe kamienice, fontanna Neptuna, ratusz."},
        {"name": "Muzeum II Wojny Światowej", "type": "museum", "rating": 4.9, "price": "25 PLN",
         "description": "Imponujące muzeum w nowoczesnym budynku. 3-4 godziny zwiedzania."},
        {"name": "Bazylika Mariacka", "type": "church", "rating": 4.7, "price": "10 PLN",
         "description": "Największy ceglany kościół na świecie. Wejdź na wieżę po widok."},
        {"name": "Westerplatte", "type": "historical", "rating": 4.6, "price": "Free",
         "description": "Miejsce wybuchu II wojny światowej. Pomnik i ruiny."},
        {"name": "Europejskie Centrum Solidarności", "type": "museum", "rating": 4.8, "price": "20 PLN",
         "description": "Historia Solidarności i upadku komunizmu. Interaktywne wystawy."},
        {"name": "Żuraw nad Motławą", "type": "landmark", "rating": 4.6, "price": "10 PLN",
         "description": "Najstarszy dźwig portowy w Europie. Symbol Gdańska."},
        {"name": "Rejs po Motławie", "type": "activity", "rating": 4.5, "price": "60 PLN",
         "description": "Godzinny rejs statkiem po Motławie i Martwej Wiśle."},
    ],
    "sopot": [
        {"name": "Molo w Sopocie", "type": "landmark", "rating": 4.7, "price": "10 PLN",
         "description": "Najdłuższe drewniane molo w Europie (511m). Spacer z widokiem na morze."},
        {"name": "Monte Cassino (Monciak)", "type": "landmark", "rating": 4.5, "price": "Free",
         "description": "Słynny deptak z restauracjami, klubami i Krzywym Domkiem."},
        {"name": "Opera Leśna", "type": "venue", "rating": 4.6, "price": "Varies",
         "description": "Amfiteatr w lesie. Koncerty i festiwale."},
    ],
    "warszawa": [
        {"name": "Stare Miasto i Zamek Królewski", "type": "landmark", "rating": 4.8, "price": "30 PLN",
         "description": "Odbudowane po wojnie Stare Miasto UNESCO. Zamek, Rynek, Barbakan."},
        {"name": "Muzeum Powstania Warszawskiego", "type": "museum", "rating": 4.9, "price": "25 PLN",
         "description": "Immersyjne muzeum o Powstaniu 1944. 2-3 godziny."},
        {"name": "Łazienki Królewskie", "type": "park", "rating": 4.8, "price": "Free",
         "description": "Przepiękny park z pałacem na wodzie. Koncerty Chopinowskie w niedziele."},
        {"name": "Pałac Kultury i Nauki", "type": "landmark", "rating": 4.3, "price": "25 PLN",
         "description": "Socrealistyczny wieżowiec. Taras widokowy na 30. piętrze."},
        {"name": "Muzeum POLIN", "type": "museum", "rating": 4.8, "price": "30 PLN",
         "description": "Historia Żydów polskich. Nowoczesne, interaktywne muzeum."},
        {"name": "Centrum Nauki Kopernik", "type": "museum", "rating": 4.7, "price": "40 PLN",
         "description": "Interaktywne centrum nauki. Świetne na randkę!"},
        {"name": "Wilanów", "type": "palace", "rating": 4.7, "price": "30 PLN",
         "description": "Barokowy pałac królewski z ogrodami. 'Polski Wersal'."},
    ],
    "kraków": [
        {"name": "Rynek Główny i Sukiennice", "type": "landmark", "rating": 4.9, "price": "Free",
         "description": "Największy średniowieczny rynek w Europie. Kościół Mariacki, Sukiennice."},
        {"name": "Wawel", "type": "castle", "rating": 4.8, "price": "30 PLN",
         "description": "Zamek królewski i katedra. Groby królewskie, Dzwon Zygmunta."},
        {"name": "Kazimierz", "type": "district", "rating": 4.7, "price": "Free",
         "description": "Dzielnica żydowska. Synagogi, knajpki, street art. Świetna na wieczór."},
        {"name": "Kopalnia Soli Wieliczka", "type": "museum", "rating": 4.8, "price": "100 PLN",
         "description": "Podziemne miasto z soli. Kaplica św. Kingi. 3 godziny zwiedzania."},
        {"name": "Kopiec Kościuszki", "type": "landmark", "rating": 4.5, "price": "20 PLN",
         "description": "Widok na cały Kraków i Tatry. Romantyczny zachód słońca."},
    ],
    "wrocław": [
        {"name": "Rynek i Ratusz", "type": "landmark", "rating": 4.8, "price": "Free",
         "description": "Jeden z najpiękniejszych rynków w Polsce. Kolorowe kamienice."},
        {"name": "Ostrów Tumski", "type": "landmark", "rating": 4.7, "price": "Free",
         "description": "Najstarsza część Wrocławia. Katedra, most Tumski, latarnik."},
        {"name": "Panorama Racławicka", "type": "museum", "rating": 4.7, "price": "30 PLN",
         "description": "Ogromne panoramiczne malowidło batalistyczne. Unikat."},
        {"name": "Szukanie Krasnali", "type": "activity", "rating": 4.6, "price": "Free",
         "description": "600+ krasnali rozsianych po mieście. Świetna zabawa na randkę."},
        {"name": "Hala Stulecia", "type": "landmark", "rating": 4.5, "price": "15 PLN",
         "description": "UNESCO. Pokazy fontann multimedialnych wieczorem."},
    ],
    "poznań": [
        {"name": "Stary Rynek i Koziołki", "type": "landmark", "rating": 4.7, "price": "Free",
         "description": "Ratusz z koziołkami trykającymi się o 12:00. Kolorowe kamieniczki."},
        {"name": "Ostrów Tumski", "type": "landmark", "rating": 4.6, "price": "Free",
         "description": "Katedra, groby pierwszych władców Polski."},
        {"name": "Cytadela", "type": "park", "rating": 4.5, "price": "Free",
         "description": "Największy park w mieście. Muzea, rzeźby, tereny zielone."},
    ],
    "łódź": [
        {"name": "Piotrkowska", "type": "landmark", "rating": 4.6, "price": "Free",
         "description": "Najdłuższy deptak handlowy w Polsce (4.2 km). Restauracje, puby, street art."},
        {"name": "Manufaktura", "type": "shopping", "rating": 4.5, "price": "Free",
         "description": "Centrum handlowo-rozrywkowe w odrestaurowanej fabryce. Kino, restauracje."},
        {"name": "Księży Młyn", "type": "district", "rating": 4.4, "price": "Free",
         "description": "Zrewitalizowane osiedle fabryczne. Lofty, galerie, klimat."},
    ],
    "katowice": [
        {"name": "Strefa Kultury", "type": "district", "rating": 4.6, "price": "Free",
         "description": "NOSPR, Muzeum Śląskie, MCK. Nowoczesna architektura na terenach pokopalnianych."},
        {"name": "Nikiszowiec", "type": "district", "rating": 4.7, "price": "Free",
         "description": "Zabytkowe osiedle górnicze. Czerwone cegły, klimatyczne uliczki."},
    ],
}

EUROPE_ATTRACTIONS = {
    "berlin": [
        {"name": "Brama Brandenburska", "type": "landmark", "rating": 4.7, "price": "Free"},
        {"name": "Reichstag", "type": "landmark", "rating": 4.6, "price": "Free (rejestracja)"},
        {"name": "Mur Berliński / East Side Gallery", "type": "historical", "rating": 4.6, "price": "Free"},
        {"name": "Wyspa Muzeów", "type": "museum", "rating": 4.8, "price": "19 EUR"},
        {"name": "Pomnik Holokaustu", "type": "memorial", "rating": 4.7, "price": "Free"},
        {"name": "Alexanderplatz i Wieża TV", "type": "landmark", "rating": 4.4, "price": "25 EUR"},
    ],
    "prague": [
        {"name": "Zamek Praski", "type": "castle", "rating": 4.7, "price": "250 CZK"},
        {"name": "Most Karola", "type": "landmark", "rating": 4.8, "price": "Free"},
        {"name": "Rynek Staromiejski i Zegar Astronomiczny", "type": "landmark", "rating": 4.8, "price": "Free"},
        {"name": "Dzielnica Żydowska (Josefov)", "type": "historical", "rating": 4.6, "price": "350 CZK"},
        {"name": "Petřín i Wieża Widokowa", "type": "park", "rating": 4.5, "price": "150 CZK"},
    ],
    "vienna": [
        {"name": "Pałac Schönbrunn", "type": "palace", "rating": 4.8, "price": "22 EUR"},
        {"name": "Katedra św. Szczepana", "type": "church", "rating": 4.7, "price": "Free"},
        {"name": "Belweder i Klimt", "type": "museum", "rating": 4.7, "price": "16 EUR"},
        {"name": "Hofburg", "type": "palace", "rating": 4.6, "price": "15 EUR"},
        {"name": "Wiener Prater i Diabelski Młyn", "type": "park", "rating": 4.5, "price": "14 EUR"},
        {"name": "Opera Wiedeńska", "type": "venue", "rating": 4.8, "price": "10-200 EUR"},
    ],
    "budapest": [
        {"name": "Parlament Węgierski", "type": "landmark", "rating": 4.9, "price": "3500 HUF"},
        {"name": "Bastion Rybacki", "type": "landmark", "rating": 4.8, "price": "Free (taras: 1000 HUF)"},
        {"name": "Termy Széchenyi", "type": "spa", "rating": 4.6, "price": "6500 HUF"},
        {"name": "Zamek Królewski w Budzie", "type": "castle", "rating": 4.7, "price": "Free"},
        {"name": "Rejs po Dunaju", "type": "activity", "rating": 4.7, "price": "15 EUR"},
    ],
    "barcelona": [
        {"name": "Sagrada Familia", "type": "church", "rating": 4.9, "price": "26 EUR"},
        {"name": "Park Güell", "type": "park", "rating": 4.7, "price": "10 EUR"},
        {"name": "La Rambla", "type": "landmark", "rating": 4.5, "price": "Free"},
        {"name": "Gothic Quarter", "type": "district", "rating": 4.7, "price": "Free"},
        {"name": "Camp Nou", "type": "stadium", "rating": 4.6, "price": "28 EUR"},
    ],
    "paris": [
        {"name": "Wieża Eiffla", "type": "landmark", "rating": 4.7, "price": "28 EUR"},
        {"name": "Luwr", "type": "museum", "rating": 4.8, "price": "17 EUR"},
        {"name": "Montmartre i Sacré-Cœur", "type": "district", "rating": 4.7, "price": "Free"},
        {"name": "Katedra Notre-Dame", "type": "church", "rating": 4.8, "price": "Free"},
        {"name": "Rejs po Sekwanie", "type": "activity", "rating": 4.6, "price": "15 EUR"},
    ],
    "rome": [
        {"name": "Koloseum", "type": "landmark", "rating": 4.7, "price": "18 EUR"},
        {"name": "Forum Romanum", "type": "historical", "rating": 4.7, "price": "W cenie Koloseum"},
        {"name": "Watykan i Bazylika św. Piotra", "type": "church", "rating": 4.9, "price": "Free (muzea: 17 EUR)"},
        {"name": "Fontanna di Trevi", "type": "landmark", "rating": 4.7, "price": "Free"},
        {"name": "Panteon", "type": "landmark", "rating": 4.8, "price": "5 EUR"},
    ],
    "london": [
        {"name": "Tower of London", "type": "castle", "rating": 4.7, "price": "30 GBP"},
        {"name": "British Museum", "type": "museum", "rating": 4.8, "price": "Free"},
        {"name": "London Eye", "type": "landmark", "rating": 4.6, "price": "30 GBP"},
        {"name": "Buckingham Palace", "type": "palace", "rating": 4.5, "price": "Free (z zewnątrz)"},
        {"name": "Tower Bridge", "type": "landmark", "rating": 4.7, "price": "12 GBP"},
    ],
}
